version: 2.1

orbs:  
  python: circleci/python@1.0.0

jobs:  
  build-and-test:    
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Log in to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PAS
      - run:
          name: Build from dockerfile
          command: |
            docker-compose up --build
      - run:
          name: Tag stuff
          command: docker tag latest $DOCKER_USER/latest
      - run:
          name: Push image ig
          command: docker push vedhasankar/latest
      - run:
          name: Compose Up
          command: docker-compose up
      # - run:
      #     name: Install Dependencies
      #     command: pip install -r requirements.txt
      # - run:
      #     name: Run file
      #     command: uvicorn app:app --reload
    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - main